# Generated by Django 5.0.7 on 2024-08-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.flat'),
        ),
    ]
